apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployments-simple-deployment-privileged-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployments-simple-deployment-privileged-app
  template:
    metadata:
      labels:
        app: deployments-simple-deployment-privileged-app
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - /bin/sh
            - -c
            - sleep 3600
